server:
  ip: 192.168.100.135
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/geek_qi/AG-Config.git
    inetutils:
      preferred-networks: ${server.ip}
      default-ip-address: ${server.ip}
      default-hostname: ${server.ip}
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.100.135:8761/eureka/
  instance:
    instance-id: ${server.ip}:${server.port}
    hostname: ${server.ip}
    ip-address: ${server.ip}
    prefer-ip-address: true