spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/geek_qi/AG-Config.git
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.96.8.208:8761/eureka/,http://47.96.8.208:8761/eureka/
